### ISSUE TITLE
watch with options failed with runtime error

### ISSUE THREAD

**Issue by dannypsnl** [kentookura/forest-server#2]
### Status

```
$ forest watch -- "build --dev --root dan-0001 trees"
 INFO  forest::server > Server started, listening on port 8080
 INFO  forest::watch  > Initial Build:
 ERROR watchexec::watchexec > runtime error err=cannot send event from fs watcher: sending into a full channel
 ERROR watchexec::watchexec > runtime error err=cannot send event from fs watcher: sending into a full channel
```

### Expected

There should have no runtime error

### Reproduce

1. Run command `forest watch -- "build --dev --root dan-0001 trees"` on https://hg.sr.ht/~dannypsnl/blog

**Comment by dannypsnl** [comment]
I already "solve" the problem, basically, you cannot just watch current directory without fear, the `.git` and `.hg` kill the application just like above.

**Comment by dannypsnl** [comment]
My bad, I forgot my plan that move to mercurial, now it's at https://hg.sr.ht/~dannypsnl/blog

**Comment by kentookura** [comment]
ah, didn't realize `hg` is for mercurial. 
We should make use of this somehow:
https://docs.rs/watchexec-filterer-ignore/latest/watchexec_filterer_ignore/struct.IgnoreFilterer.html

**Comment by kentookura** [comment]
https://github.com/watchexec/watchexec/blob/44d794c92151a392467c813eeb255ee48ddf3c68/crates/cli/src/filterer/globset.rs

**Comment by dannypsnl** [comment]
I think an elementary way is
1. list the current directory
2. rule out unwatned, e.g. `.hg`, `.git`
3. rest paths are the initial watch set

**Comment by kentookura** [comment]
I am currently adapting this implementation for our usecase:
https://github.com/watchexec/watchexec/blob/main/crates/cli/src/filterer/globset.rs
I am still confused why this error occurs, since we are filtering out events for files that do not end with "tree":
https://github.com/kentookura/forest-server/blob/f0887185474a22cf0cab454949ca21d1a8e1b36d/src/watch.rs#L32

**Comment by dannypsnl** [comment]
Not weird at all to me, the filter remove event not from 'tree', but event still there, from watcher.

I will start my PR then.
