### ISSUE TITLE
Check nix build in CI

### ISSUE THREAD

**Issue by kentookura** [kentookura/forest-server#5]
CI currently doesn't check if the nix build succeeds.

**Comment by NickHu** [comment]
You could also push the build result to cachix.org, so that users can avoid having to rebuild too. It might also be better to use the rust compiler provided by nixpkgs (or at least use rust stable) instead to minimize closure size too.

**Comment by kentookura** [comment]
We are now using the stable toolchain and using this cache: https://app.cachix.org/cache/forester
https://github.com/kentookura/forest-server/commit/a689596af66d0845319b68b8b40b4c520e2e0841
